// One-time script: adds 275 new questions (55 per topic) under 5 new business-title
// categories: Law, Shop, Hired, Customer, Saving - split across members/pro tiers.
// Continues questionNumber sequence from 176 (current max is 175 after the Bonus batch).
require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('./models/Question');

const LAW = [
  [`Which legal entity - sole proprietorship, LLC, S-Corp, or partnership - fits your situation, and why?`, `A freelance consultant is deciding between staying a sole proprietor or forming an LLC.`],
  [`What is the exact process to register your business name with your state?`, `A new owner has chosen a name but has not filed anything with the state yet.`],
  [`Which federal, state, and local licenses does your specific trade require before you can legally open?`, `A mobile pet grooming business is unsure which licenses apply beyond a basic business license.`],
  [`How do you get an Employer Identification Number, and why do you need one even as a solo owner?`, `A single-member LLC owner has been using their personal SSN for business banking.`],
  [`What zoning rules apply to your location, and have you confirmed your business type is allowed there?`, `A home baker wants to start selling from a rented commercial kitchen space.`],
  [`Which health department permits apply if your business touches food, health, or personal care?`, `A new food truck has a menu ready but no health inspection scheduled yet.`],
  [`What professional license does your trade require, and is it current for everyone on your team?`, `A contracting business is adding a second licensed electrician to the crew.`],
  [`How do you register for state sales tax and know which of your products or services are taxable?`, `An online store is unsure if digital downloads are taxed the same as physical goods.`],
  [`What payroll tax obligations apply the moment you hire your first employee?`, `A business about to make its first hire has never run payroll before.`],
  [`How often are estimated quarterly tax payments due, and have you set aside money for the next one?`, `A profitable first year caught an owner off guard with an estimated tax bill.`],
  [`What should a founders agreement cover if you are starting a business with a partner?`, `Two friends are splitting ownership 50/50 with nothing in writing yet.`],
  [`What happens to ownership if a cofounder wants to leave the business?`, `A three-person partnership has never discussed what an exit would look like.`],
  [`Which clauses in your commercial lease actually matter beyond the monthly rent figure?`, `A retailer is about to sign a five-year lease without reading the renewal terms.`],
  [`What should a vendor contract specify about minimum orders, pricing changes, and delivery delays?`, `A manufacturer relies on one overseas supplier with no written delivery guarantee.`],
  [`How do you protect your business name with a trademark, not just a state registration?`, `A new brand has not checked if its name conflicts with an existing trademark.`],
  [`What insurance coverage - general liability, professional liability, property - does your business actually need in year one?`, `A home-based consultant is unsure if liability insurance is worth the premium.`],
  [`How do you correctly classify a worker as an employee versus an independent contractor?`, `A growing studio is unsure if their instructors should be contractors or employees.`],
  [`What does your employee handbook need to include to be legally sound?`, `A ten-person company has never written a formal handbook.`],
  [`How do you handle a workplace complaint about harassment or discrimination the right way?`, `An owner has never had to investigate a formal employee complaint before.`],
  [`What data privacy obligations apply if your business stores customer payment or personal information?`, `An online shop stores customer addresses and card data with no written privacy policy.`],
  [`What is required to legally dissolve a business if you decide to close it?`, `A sole proprietor wants to shut down but is unsure what filings are required.`],
  [`How do you handle sales tax if you sell to customers in multiple states?`, `An online store just started shipping to five new states this year.`],
  [`What contract terms protect you when hiring a freelance or outside contractor?`, `A business hired a freelance designer with only a verbal agreement on scope.`],
  [`How do you register a trademark for your logo in addition to your business name?`, `A brand has a recognizable logo but has never filed for trademark protection.`],
  [`What permits apply if you plan to serve alcohol as part of your business?`, `A new restaurant wants to add a beer and wine license to its concept.`],
  [`How do you handle the legal side of a business partnership buyout?`, `One partner in a two-person business wants to buy out the other.`],
  [`What should an employment offer letter include to avoid future disputes?`, `A business has been hiring with only a verbal job offer and start date.`],
  [`How do you protect confidential business information when working with contractors or vendors?`, `A business shares pricing and client lists with an outside marketing contractor.`],
  [`What is required to legally operate a home-based business in your city?`, `A candle maker runs the business from a spare room with no home occupation permit.`],
  [`How do you handle intellectual property ownership for work created by employees or contractors?`, `A design studio never specified who owns the artwork contractors create for clients.`],
  [`What ADA accessibility requirements apply to your physical location?`, `A storefront built decades ago has never been evaluated for accessibility compliance.`],
  [`How do you set up a legally compliant referral or affiliate program?`, `A business wants to pay other businesses for referred customers but has no written terms.`],
  [`What record-keeping requirements apply so you can survive a tax audit?`, `A business keeps receipts in a shoebox with no organized system.`],
  [`How do you handle a customer dispute that escalates to a legal demand letter?`, `A business received a formal demand letter over a service complaint.`],
  [`What is required to legally advertise a sale or discount without misleading customers?`, `A retailer wants to advertise "50% off" pricing that was never the regular price.`],
  [`How do you structure a non-compete or non-solicitation agreement that will actually hold up?`, `A business wants to prevent a departing employee from poaching clients.`],
  [`What permits are required to operate a food truck or mobile business across multiple cities?`, `A food truck wants to expand service into two neighboring counties.`],
  [`How do you handle legal compliance when shipping products internationally?`, `An online store just received its first order from a customer overseas.`],
  [`What is required to add a business partner or investor to an existing LLC?`, `A solo LLC owner wants to bring on an investor for the first time.`],
  [`How do you make sure your website has the legal disclosures customers expect, like a privacy policy and terms of service?`, `A new e-commerce site launched without a privacy policy or refund policy posted.`],
  [`What steps protect you legally if a customer is injured on your premises?`, `A gym wants to make sure its liability waiver actually holds up.`],
  [`How do you handle the legal requirements of a business name change?`, `A rebrand requires updating the business name on every registration and account.`],
  [`What is required to legally franchise your business if others want to open locations?`, `A three-location business keeps getting asked about franchising opportunities.`],
  [`How do you make sure your marketing claims about your product comply with advertising law?`, `A supplement company wants to make health claims in its ads.`],
  [`What is the legal process to convert an LLC into a corporation as you grow?`, `An LLC is preparing to raise outside investment and may need to convert.`],
  [`How do you handle warranty or guarantee language so it is legally enforceable, not just marketing?`, `A furniture maker advertises a lifetime warranty with no written terms.`],
  [`What legal steps protect your business if a vendor fails to deliver as promised?`, `A retailer lost a season of inventory when a supplier missed shipment dates.`],
  [`How do you handle legal requirements for collecting and remitting tips for tipped employees?`, `A restaurant is unsure how tip pooling affects payroll tax reporting.`],
  [`What is required to add workers compensation insurance once you have employees?`, `A business hired its first two employees without workers compensation coverage.`],
  [`How do you handle a legal review of your standard customer contract before using it widely?`, `A service business has used the same contract template for three years without review.`],
  [`What permits are required if your business involves environmental concerns like waste disposal?`, `An auto repair shop disposes of used oil without a documented process.`],
  [`How do you protect your business if a key vendor contract is breached?`, `A supplier failed to deliver under contract, costing a business a major client.`],
  [`What is required to legally collect and store customer email addresses for marketing?`, `A business built an email list without a clear opt-in process.`],
  [`How do you handle legal compliance when offering gift cards or store credit?`, `A retailer sells gift cards but has not checked state expiration rules.`],
  ['What steps ensure your business is properly insured against a data breach?', 'An online store processes payments but has never reviewed cyber liability coverage.']
];

const SHOP = [
  [`Does your location actually put you in front of the customer you are trying to reach?`, `A high-end boutique is considering a location near budget retail instead of upscale shops.`],
  [`Is your space the right size for your actual sales volume and foot traffic?`, `A shop feels empty most days but turns customers away during weekend rushes.`],
  [`What businesses are within a five-minute walk, and what do they tell you about your customer base?`, `A new cafe has not mapped the surrounding businesses near its location.`],
  [`What percentage of people who pass your location actually come inside?`, `A storefront with heavy foot traffic has never measured its conversion rate.`],
  [`What happens to your rent and lease terms by year three of your lease?`, `A retailer signed a lease without asking about rent escalation clauses.`],
  [`If your current location failed, where would you go instead, and why?`, `A business has never considered a backup location in case of relocation.`],
  [`How much parking does your location realistically offer your customers?`, `A suburban store relies on street parking that fills up during peak hours.`],
  [`Is your signage visible enough for someone unfamiliar with the area to find you?`, `A shop is tucked behind another building with no street-facing sign.`],
  [`How does your store layout guide customers toward your highest-margin products?`, `A retail floor plan has never been tested against actual customer walking patterns.`],
  [`What is your plan if your landlord raises rent significantly at renewal?`, `A tenant has no leverage planned for an upcoming lease renewal negotiation.`],
  [`How do you decide between a strip mall, standalone building, or mixed-use development?`, `A new business is comparing three very different types of available locations.`],
  [`What does your competitor down the street do better than you, based on their reviews?`, `A competing shop two blocks away has noticeably higher ratings.`],
  [`How accessible is your location for customers with disabilities?`, `An older building has stairs at the only entrance with no ramp.`],
  [`What is your plan for inventory storage as your product line grows?`, `A boutique is running out of backroom space for new seasonal inventory.`],
  [`How do you decide if a second location is actually justified by demand?`, `A single-location restaurant has had six strong months and is considering expansion.`],
  [`What hours of operation actually match when your real customers want to shop?`, `A store is open 9 to 5 but most foot traffic arrives in the evening.`],
  [`How do you evaluate whether your location has safety or security concerns?`, `A shop in a busy area has had two break-ins this year.`],
  [`What utilities and infrastructure does your space need that it does not currently have?`, `A commercial space lacks the electrical capacity for new kitchen equipment.`],
  [`How do you handle a renovation decision that would temporarily close your business?`, `A shop needs a major remodel but cannot afford to lose a month of revenue.`],
  [`What is your fallback plan if your primary location becomes unusable overnight?`, `A business has never planned for a fire, flood, or sudden closure.`],
  [`How does delivery radius or service area affect where you should be located?`, `A meal prep business is deciding how far to drive for deliveries.`],
  [`What does your foot traffic pattern look like by day of week and time of day?`, `A shop assumes weekends are busiest but has never measured it.`],
  [`How do you decide whether to renovate your current space or relocate entirely?`, `An aging storefront needs updates that may cost as much as moving.`],
  [`What is the real cost difference between buying your location versus continuing to lease?`, `A profitable business has been offered the chance to buy its building.`],
  [`How do you evaluate whether nearby anchor businesses bring you real customer traffic?`, `A shop located near a large grocery store assumes it benefits from the traffic.`],
  [`What changes would you make to your storefront window display to draw more customers in?`, `A boutique's window has not been updated in over a year.`],
  [`How do you decide if your location needs a dedicated loading or receiving area?`, `A growing retailer struggles to unload deliveries on a narrow street.`],
  [`What is your plan if a major nearby business that drives your traffic closes?`, `A shop relies heavily on spillover traffic from a popular neighboring restaurant.`],
  [`How do you evaluate whether your current location limits your growth?`, `A business has hit a sales ceiling that may be tied to its space.`],
  [`What noise, smell, or environmental factors from your location could affect customers?`, `A bakery next to an auto shop deals with occasional exhaust smell complaints.`],
  [`How do you plan your layout to reduce customer wait times at checkout?`, `A store's checkout line regularly backs up into the main aisle.`],
  [`What is the right amount of storage versus customer-facing space for your business?`, `A shop has more backroom space than it uses while the sales floor feels cramped.`],
  [`How do you decide if your location should offer curbside pickup or delivery options?`, `A retailer has not considered whether its parking lot supports curbside service.`],
  [`What seasonal changes in foot traffic should shape your staffing and hours?`, `A beach-town shop sees huge swings between summer and winter traffic.`],
  [`How do you evaluate a location's visibility from the road for passing traffic?`, `A shop set back from the street is easy to miss while driving by.`],
  [`What is your plan if construction nearby disrupts access to your location?`, `A storefront is about to face months of road construction out front.`],
  [`How do you decide whether shared space with another business makes sense for you?`, `A small retailer is considering splitting rent with a complementary business.`],
  [`What does your current space tell customers about your brand before they even enter?`, `A premium brand operates from a space that looks worn and outdated.`],
  [`How do you evaluate whether your location needs better exterior lighting for evening hours?`, `A shop open until 9pm has a dimly lit parking area.`],
  [`What is your plan for handling a lease that does not renew?`, `A tenant just learned their landlord will not offer a new lease term.`],
  [`How do you decide if moving to a pop-up or temporary space makes sense before committing long-term?`, `A new concept wants to test demand before signing a long lease.`],
  [`What role does public transit access play in who can reach your location?`, `A shop near a bus line has never measured how many customers arrive by transit.`],
  [`How do you evaluate whether your space allows for efficient staff movement during busy hours?`, `Employees constantly bump into each other behind a narrow counter.`],
  [`What is your plan if you need more square footage but cannot expand your current space?`, `A growing business is boxed in by neighboring tenants on both sides.`],
  [`How do you decide between multiple smaller locations versus one larger flagship location?`, `A brand is weighing opening three small shops versus one large store.`],
  [`What does your current rent cost as a percentage of your monthly revenue, and is that sustainable?`, `A business has never calculated rent as a percentage of sales.`],
  [`How do you evaluate whether your location's demographics match your target customer?`, `A premium service business operates in a neighborhood with a different income profile.`],
  [`What is your plan for managing deliveries and vendor drop-offs without disrupting customers?`, `Vendor trucks block the customer entrance during busy morning hours.`],
  [`How do you decide if outdoor seating or signage requires a separate permit at your location?`, `A cafe wants to add sidewalk seating without checking city rules.`],
  [`What does the five-year development plan for your neighborhood mean for your location?`, `A city is planning road changes that could affect access to a business.`],
  [`How do you evaluate a location's internet and connectivity reliability for your operations?`, `A business depends on card payments but has frequent internet outages.`],
  [`What is your plan if your landlord sells the building to a new owner?`, `A tenant just learned their building sold and the new owner's plans are unclear.`],
  [`How do you decide whether your current space supports future equipment or technology upgrades?`, `A restaurant wants new kitchen equipment that may not fit the current layout.`],
  ['What would it take to make your location more attractive to your highest-value customers specifically?', 'A shop attracts casual browsers but struggles to draw its ideal high-spending customer.'],
  [`How do you decide whether a shared parking lot is adequate for your peak-hour customer volume?`, `A plaza's shared lot fills up completely during the Saturday lunch rush.`]
];

const HIRED = [
  [`What is the one task only you can do right now, and who could take the rest off your plate?`, `An owner is personally handling scheduling, sales, and cleanup every day.`],
  [`Are you hiring for skill, for cultural fit, or do you need both equally?`, `A technically skilled candidate does not seem to match the team's working style.`],
  [`Have you calculated what a role actually costs over a full year, not just the hourly wage?`, `A business is comparing two wage offers without factoring in payroll taxes.`],
  [`Could you describe, in one sentence, what success looks like for this role?`, `A new hire was never given a clear picture of what a great week looks like.`],
  [`Are you confident the people working for you are classified correctly as employees or contractors?`, `A business has three "contractors" who work the exact same hours every week.`],
  [`Do you have a real plan for a new hire's first day and first week?`, `New employees have historically figured things out on their own with no onboarding.`],
  [`How do you write a job posting that attracts the right candidates, not just more applicants?`, `A posting for a customer service role keeps attracting unqualified applicants.`],
  [`What interview questions actually predict whether someone will succeed in this specific role?`, `Past hires who interviewed well have struggled once on the job.`],
  [`How do you structure a fair and motivating commission or bonus plan for a sales role?`, `A flat commission structure is pushing reps to discount heavily just to close deals.`],
  [`What would you do if a long-time employee is underperforming in one specific area?`, `A five-year employee is excellent with customers but misses every deadline.`],
  [`How do you build a career path so good employees do not leave for lack of growth?`, `A strong performer mentioned they feel stuck with no path forward.`],
  [`What should your employee handbook cover that it currently does not?`, `A ten-person business has never had a written handbook.`],
  [`How do you handle a conflict between two employees affecting team morale?`, `Two senior staff members have an ongoing disagreement the rest of the team notices.`],
  [`When is it time to add a manager layer between you and your growing team?`, `An owner now has fourteen people reporting directly to them.`],
  [`What does a fair exit process look like when an employee resigns?`, `A key employee just gave notice and holds several important client relationships.`],
  [`How do you build a scheduling system that matches labor costs to actual demand?`, `A cafe is overstaffed on slow mornings and understaffed on weekends.`],
  [`What training would actually improve consistency across your team's service quality?`, `Customer satisfaction varies noticeably depending on which employee handles the job.`],
  [`How do you decide if someone should move from contractor to full employee status?`, `A contractor now works full-time, ongoing hours indistinguishable from an employee.`],
  [`What is your plan for cross-training so no single employee becomes a single point of failure?`, `One employee holds all the knowledge of a key client relationship.`],
  [`How do you handle a request for remote or flexible work from an in-person role?`, `An administrative employee asked to work from home two days a week.`],
  [`What should a performance improvement plan actually include to give someone a real chance?`, `An employee is struggling but has never received a formal improvement plan.`],
  [`How do you decide fair pay increases without creating inequity across the team?`, `A valued employee came in with a competing offer paying 20% more.`],
  [`What onboarding materials would help a new hire ramp up faster?`, `New hires take months to become fully productive with no training documents.`],
  [`How do you build a hiring plan that anticipates growth instead of reacting to it?`, `A business landed a big contract and now needs to hire quickly.`],
  [`What should you look for in a candidate's references beyond confirming dates of employment?`, `A hiring manager calls references but only confirms basic employment facts.`],
  [`How do you handle seasonal staffing surges without overcommitting to permanent payroll?`, `A landscaping company needs double the staff for six months a year.`],
  [`What is your process for terminating an employee in a way that is fair and legally sound?`, `An owner has never had to formally terminate someone before.`],
  [`How do you recognize strong performance without a large budget for raises or bonuses?`, `A business wants to retain a top performer but cannot afford a raise right now.`],
  [`What should a new manager be trained on before taking on direct reports?`, `A top performer was just promoted into their first management role.`],
  [`How do you handle overtime and scheduling fairly for hourly employees?`, `A restaurant has had disputes over which shifts count toward overtime.`],
  [`What would make your team's first week of training more effective?`, `New hires receive the same generic training regardless of their specific role.`],
  [`How do you decide which roles can be remote versus which require being on-site?`, `A business is building its first fully remote position.`],
  [`What steps ensure a new hire's paperwork and compliance are handled correctly from day one?`, `A rushed hire started working before tax forms were completed.`],
  [`How do you build a referral program that encourages employees to recommend good candidates?`, `A business relies entirely on job postings and has never asked current staff for referrals.`],
  [`What would a six-month check-in reveal about a new hire that a 90-day review would not?`, `A new hire's performance has shifted significantly since their initial review.`],
  [`How do you handle a situation where an employee's personal issues are affecting their work?`, `A normally reliable employee has started missing shifts without explanation.`],
  [`What should your interview process test for that a resume alone cannot show?`, `A candidate's resume looks perfect but something feels uncertain after the interview.`],
  [`How do you decide the right ratio of full-time staff to part-time or seasonal help?`, `A business relies heavily on part-time staff and wonders if that is sustainable.`],
  [`What does your exit interview process reveal about why people actually leave?`, `Three employees have left in the past year with no formal exit conversation.`],
  [`How do you build trust with a new manager so the team respects their authority?`, `A newly promoted manager is struggling to get buy-in from former peers.`],
  [`What should your job description include about growth opportunities to attract ambitious candidates?`, `A posting lists duties and pay but says nothing about advancement.`],
  [`How do you handle disagreements about pay between employees in similar roles?`, `Two employees in the same position discovered they are paid differently.`],
  [`What would an anonymous employee survey reveal about morale that you are not seeing?`, `An owner assumes the team is happy but has never actually asked.`],
  [`How do you decide when a role needs to be split into two separate positions?`, `One employee is juggling responsibilities that used to be two different jobs.`],
  [`What should a layoff conversation include to treat an employee with respect?`, `A slow season is forcing a difficult staffing reduction decision.`],
  [`How do you build a mentorship system that pairs new hires with experienced staff?`, `New employees have no one assigned to answer their day-to-day questions.`],
  [`What would it take to reduce turnover in your highest-turnover role?`, `One specific position consistently has the shortest average tenure on the team.`],
  [`How do you evaluate whether your interview process has any unconscious bias?`, `A hiring manager has never reviewed their own interview process for fairness.`],
  [`What should your job offer letter include beyond just salary and start date?`, `Past hires have been confused about benefits and expectations after accepting an offer.`],
  [`How do you decide whether to promote from within or hire externally for a leadership role?`, `A team has a strong internal candidate but also external applicants with more experience.`],
  [`What would make your probationary period a genuine evaluation rather than a formality?`, `New hires pass their 90-day review automatically regardless of performance.`],
  [`How do you handle a top performer who wants a title change without more responsibility?`, `A strong employee wants a senior title but is not ready for added duties.`],
  [`What should your succession plan look like for a role only one person can currently do?`, `A key employee has not taken a vacation in two years because no one can cover them.`],
  ['How do you build a culture where employees feel safe reporting mistakes early?', 'Small errors have been getting hidden until they become bigger problems.'],
  [`How do you decide the right notice period to require from employees who resign?`, `An employee gave only three days notice, leaving no time to plan coverage.`]
];

const CUSTOMER = [
  [`Can you name the exact moment in your service that makes a customer genuinely happy?`, `A business assumes friendly staff alone is enough to satisfy customers.`],
  [`What is the one thing that, if it goes wrong, reliably turns a customer against you?`, `A business has never identified its specific most common failure point.`],
  [`How do you know if your average customer is satisfied or just quietly tolerating you?`, `Repeat visit rates have slipped with no complaints to explain why.`],
  [`If you had to describe your one ideal customer in a single sentence, what would you say?`, `A business tries to appeal to everyone and struggles to stand out to anyone.`],
  [`Do you actually know how most of your customers first heard about you?`, `Marketing spend is split across channels with no tracking of what works.`],
  [`What gives a customer a reason to come back instead of trying a competitor next time?`, `First-time customers rarely return for a second visit.`],
  [`How do you handle a customer complaint in a way that keeps the relationship intact?`, `A recent complaint was resolved but the customer never came back.`],
  [`What would your best customers say if asked why they keep choosing you?`, `A business has never directly asked its most loyal customers this question.`],
  [`How do you measure customer satisfaction beyond just watching for complaints?`, `A business assumes no complaints means customers are happy.`],
  [`What does your return or refund policy actually communicate to customers about trust?`, `A strict no-refund policy may be discouraging first-time buyers.`],
  [`How do you build a loyalty program that rewards the behavior you actually want?`, `A punch-card program has low participation and unclear value to customers.`],
  [`What do your negative reviews have in common, and what would fixing that one thing change?`, `Several reviews mention the same complaint but nothing has changed.`],
  [`How do you personalize the customer experience without it feeling intrusive?`, `A business collects customer data but never uses it to improve service.`],
  [`What is your plan for responding to negative reviews publicly and professionally?`, `A one-star review has gone unanswered for weeks.`],
  [`How do you segment your customers to serve different groups more effectively?`, `A business treats every customer the same despite very different needs.`],
  [`What would make your onboarding experience for new customers smoother?`, `New customers often seem confused during their first interaction with the business.`],
  [`How do you calculate the lifetime value of your average customer?`, `A business has never estimated what a customer is worth over time, only per visit.`],
  [`What is your plan for win-back outreach to customers who have not returned in months?`, `A list of past customers has never been re-contacted after they stopped buying.`],
  [`How do you train staff to handle an upset customer without escalating the situation?`, `A recent customer interaction turned a minor issue into a public complaint.`],
  [`What would a mystery shopper experience reveal about your actual customer service?`, `An owner assumes service is consistent but has never tested it directly.`],
  [`How do you decide which customer feedback to act on versus which to set aside?`, `Feedback is collected but never reviewed or acted upon.`],
  [`What is your plan for keeping customers informed when something goes wrong, like a delay?`, `Customers found out about a delay only when they called to ask.`],
  [`How do you build a referral system that turns happy customers into active promoters?`, `Satisfied customers rarely refer others because there is no simple way to do it.`],
  [`What would it take to turn a merely satisfied customer into an enthusiastic one?`, `Most customers seem fine but few seem genuinely excited about the business.`],
  [`How do you handle a customer who is chronically difficult but still profitable?`, `One recurring client consumes a disproportionate amount of staff time and patience.`],
  [`What does your checkout or booking process do that might quietly frustrate customers?`, `Cart abandonment is high but no one has tested the checkout flow personally.`],
  [`How do you decide which communication channel - text, email, phone - customers actually prefer?`, `Appointment reminders are sent by email even though most customers text constantly.`],
  [`What would your competitor's unhappy customers tell you about an opportunity for your business?`, `A competitor has several recurring complaints in their public reviews.`],
  [`How do you build trust with a first-time customer who has never heard of you?`, `New customers seem hesitant until they have used the service once.`],
  [`What is your plan for handling a service failure that affects many customers at once?`, `A system outage affected every customer's order for several hours.`],
  [`How do you decide what to do when a customer asks for something outside your normal policy?`, `A loyal customer requested an exception that would set a new precedent.`],
  [`What would make your customer support easier to reach when something goes wrong?`, `Customers have complained about long wait times to get help.`],
  [`How do you use customer feedback to influence product or service decisions, not just service tweaks?`, `Feedback has only ever led to staff coaching, never to product changes.`],
  [`What is your plan for following up after a purchase to confirm satisfaction?`, `Customers are never contacted again after their purchase is complete.`],
  [`How do you identify your most profitable customer segment and serve them even better?`, `A business has never analyzed which customers generate the most profit.`],
  [`What would an exit survey from a canceling customer reveal about why they left?`, `Canceled subscribers are never asked why they stopped.`],
  [`How do you decide which complaints indicate a real pattern versus a one-off issue?`, `A single complaint led to a policy change that frustrated everyone else.`],
  [`What is your plan for rewarding long-term customers differently than new ones?`, `A five-year customer gets the exact same treatment as a first-time visitor.`],
  [`How do you make it easy for a customer to tell you when something went wrong?`, `Most dissatisfied customers simply leave without ever complaining.`],
  [`What would it take to reduce the time between a customer's question and your response?`, `Customer emails often go unanswered for more than a day.`],
  [`How do you decide whether a discount is winning new customers or just cutting your margin?`, `Frequent promotions have not clearly increased total profit.`],
  [`What is your plan for customers who interact with you across multiple channels?`, `A customer's history online and in-store is never connected.`],
  [`How do you handle a customer who leaves a public review you believe is unfair?`, `A review mischaracterizes an interaction but has not been addressed.`],
  [`What would make your product packaging or first impression more memorable?`, `Customers rarely mention the unboxing or arrival experience.`],
  [`How do you decide which customer complaints justify a policy change company-wide?`, `A single loud complaint led to a change that confused everyone else.`],
  [`What is your plan for customers who have a bad first experience but are worth winning back?`, `A rough first visit likely cost the business a repeat customer.`],
  [`How do you train every employee to deliver the same quality of service consistently?`, `Service quality depends heavily on which employee happens to help a customer.`],
  [`What would your customers say is missing from your current product or service lineup?`, `Customers occasionally ask for something the business does not currently offer.`],
  [`How do you decide when a customer relationship is no longer worth maintaining?`, `A client is profitable but consistently disrespectful to staff.`],
  [`What is your plan for celebrating a customer milestone, like their tenth order or first anniversary?`, `Long-term customers never receive any special acknowledgment.`],
  [`How do you make sure customer data collected for marketing is actually used thoughtfully?`, `An email list has grown but messages feel generic and untargeted.`],
  [`What would it take to make your customer service feel personal instead of scripted?`, `Staff follow a script that sometimes feels robotic to customers.`],
  ['How do you decide whether a customer complaint reveals a training gap or a policy flaw?', 'A recurring complaint keeps getting blamed on individual staff mistakes.'],
  [`What would it take to make your follow-up after a complaint feel genuine instead of routine?`, `A standard apology email is sent after every complaint, regardless of severity.`],
  [`How do you decide which customers deserve a proactive check-in instead of waiting for them to reach out?`, `A high-value client's order was late and no one from the business reached out first.`]
];

const SAVING = [
  [`If revenue dropped 40% for two months, could your savings cover the gap?`, `A seasonal business has never stress-tested its reserve against a real slow period.`],
  [`Does your business have its own reserve, separate from your personal savings?`, `An owner has been covering business shortfalls from personal savings.`],
  [`What specific situation would justify actually using your business reserve?`, `A reserve exists but there is no rule for when it can be spent.`],
  [`How do you decide whether this month's profit should be saved or reinvested?`, `Profit gets spent on whatever opportunity looks appealing that month.`],
  [`What would running out of cash actually cost you, beyond the money itself?`, `An owner has never considered the stress and decision-making cost of no reserve.`],
  [`Do you know where your business reserve is kept, and how fast you could access it?`, `Reserve funds sit in an account no one has reviewed in over a year.`],
  [`How much of your monthly revenue should realistically go toward savings?`, `A business saves whatever is left over, which is often nothing.`],
  [`What would it take to build a six-month expense reserve from where you are today?`, `A business has less than one month of reserve currently.`],
  [`How do you decide between paying down debt versus building your cash reserve first?`, `A business has both a loan balance and no emergency fund.`],
  [`What tax-advantaged accounts should a profitable small business owner be using?`, `An owner has never explored retirement account options for their business.`],
  [`How do you separate savings for equipment replacement from your general reserve?`, `A delivery business has no dedicated fund for an eventual vehicle replacement.`],
  [`What would an automatic savings transfer change about your current habits?`, `Savings only happen when an owner remembers to move money manually.`],
  [`How do you decide the right reserve target for a business with seasonal revenue?`, `A landscaping company earns most of its revenue in six months of the year.`],
  [`What insurance coverage could reduce how much cash reserve you actually need?`, `A business keeps a large reserve instead of carrying adequate insurance.`],
  [`How do you avoid dipping into savings for a "good opportunity" that is not a real emergency?`, `A reserve has been used twice this year for things that were not emergencies.`],
  [`What would it take to replenish your reserve after a real emergency uses it up?`, `A reserve was used during a slow month and has never been rebuilt.`],
  [`How do you decide whether a high-yield savings account is worth the extra effort to set up?`, `Business cash sits in a checking account earning no interest.`],
  [`What percentage of profit should be distributed to owners versus kept as reserve?`, `All profit has historically been distributed with nothing held back.`],
  [`How do you plan for a known large expense, like a lease renewal deposit, months in advance?`, `A lease renewal fee caught the business off guard last year.`],
  [`What would it take to build a reserve specifically for a slow season you know is coming?`, `The same quiet months happen every year with no advance preparation.`],
  [`How do you decide if a line of credit should supplement your cash reserve?`, `A business has never explored a credit line as a backup safety net.`],
  [`What would happen to your business if a single large client suddenly stopped paying?`, `Revenue is heavily concentrated in one client with no reserve to absorb the loss.`],
  [`How do you avoid mixing personal and business savings when you are a solo owner?`, `Personal and business savings currently sit in the same account.`],
  [`What would it take to save enough to self-fund your next piece of equipment instead of financing it?`, `Every equipment purchase so far has required a loan.`],
  [`How do you decide the right amount to save for an eventual slow economic period?`, `A business has never planned for a broader economic downturn.`],
  [`What would an honest calculation of your true monthly burn rate reveal?`, `An owner has never calculated the minimum monthly cost to keep the business running.`],
  [`How do you build savings discipline during your strongest months, not just your slowest?`, `Savings habits tend to lapse during busy, high-revenue periods.`],
  [`What would it take to save enough to cover a full payroll cycle without any incoming revenue?`, `Payroll has always been paid from that week's incoming revenue, with no buffer.`],
  [`How do you decide whether to save for growth or save purely for protection?`, `Extra cash has no clear purpose defined between growth and safety.`],
  [`What is your plan if a major piece of equipment fails without warning?`, `A single piece of equipment, if it broke, would stop operations entirely.`],
  [`How do you evaluate whether your current reserve is too conservative for your stage of growth?`, `A well-established business may be holding more reserve than it actually needs.`],
  [`What would it take to save toward buying out a business partner someday?`, `A two-person partnership has never discussed how a future buyout would be funded.`],
  [`How do you plan savings around a known future tax bill, not just routine quarterly payments?`, `A one-time windfall year created an unexpectedly large tax bill.`],
  [`What would it take to fund three months of marketing spend from reserve during a slow period?`, `Marketing is always the first expense cut when cash gets tight.`],
  [`How do you decide whether your reserve should be liquid cash or short-term investments?`, `All reserve funds sit in cash with no consideration of modest, safe returns.`],
  [`What would an unexpected lawsuit or legal cost do to your current cash position?`, `A business has no reserve or insurance earmarked for legal risk.`],
  [`How do you build a savings plan around eventually hiring your first employee?`, `A solo business has not calculated the true cash buffer needed before its first hire.`],
  [`What would it take to save enough to open a second location without external financing?`, `Expansion plans currently depend entirely on taking out a loan.`],
  [`How do you decide the right reserve size as your business has grown from its first year?`, `A reserve target set years ago has never been revisited since early growth.`],
  [`What would it take to save for a slow month that coincides with a planned personal expense?`, `An owner's personal and business slow periods have overlapped before, straining both.`],
  [`How do you build discipline to leave your reserve untouched even in a strong month?`, `A strong month tempts spending reserve funds on non-essential upgrades.`],
  [`What would it take to save enough to self-insure against a specific known risk in your industry?`, `A specific seasonal risk has caused cash problems in past years.`],
  [`How do you decide whether an emergency fund should cover one month or six months of expenses?`, `A reserve target has never been calculated against actual fixed costs.`],
  [`What would it take to build a reserve fund specifically for unpaid customer invoices?`, `A slow-paying client has created cash flow strain more than once.`],
  [`How do you plan savings around a major piece of insurance renewal due once a year?`, `An annual insurance premium creates a predictable but unplanned cash crunch.`],
  [`What would it take to start saving toward retirement as a business owner with no employer plan?`, `An owner has no retirement savings vehicle set up through the business.`],
  [`How do you decide whether saving in the business or saving personally serves you better long-term?`, `An owner is unsure whether to keep profit in the business or take it out.`],
  [`What would it take to build a reserve that could fund a slow relaunch after a forced closure?`, `A business has never planned for a scenario requiring a temporary full closure.`],
  [`How do you evaluate whether your savings rate today sets you up for the growth you want in five years?`, `Current saving habits have never been tied to a longer-term growth goal.`],
  [`What would it take to save enough to weather the loss of your single biggest revenue month?`, `One month accounts for a disproportionate share of annual revenue.`],
  [`How do you decide the right balance between an emergency fund and a opportunity fund?`, `All extra cash is labeled as emergency reserve with none set aside for opportunities.`],
  [`What would it take to automate moving a fixed percentage of every sale into savings?`, `Savings currently happen manually and inconsistently at the end of each month.`],
  ['How do you evaluate whether your reserve is actually keeping pace with your growing fixed costs?', 'Fixed costs have grown significantly since the reserve target was last set.'],
  [`What would it take to save enough to skip financing entirely on your next major purchase?`, `A business has financed every large purchase so far and wants to break that pattern.`],
  [`How do you decide whether idle cash sitting in your reserve should earn a better return?`, `A reserve fund has sat in a zero-interest account for three years.`]
];

const TOPICS = [
  { name: 'Law', category: 'start', items: LAW },
  { name: 'Shop', category: 'start', items: SHOP },
  { name: 'Hired', category: 'manage', items: HIRED },
  { name: 'Customer', category: 'manage', items: CUSTOMER },
  { name: 'Saving', category: 'money', items: SAVING }
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);

  let questionNumber = 176;
  const docs = [];
  for (const topic of TOPICS) {
    topic.items.forEach(([questionText, example], idx) => {
      docs.push({
        businessTitle: topic.name,
        questionText,
        example,
        category: topic.category,
        tierAccess: idx % 2 === 0 ? 'members' : 'pro',
        questionNumber: questionNumber++,
        isActive: true
      });
    });
  }

  console.log(`Prepared ${docs.length} questions.`);
  for (const doc of docs) {
    await Question.updateOne({ questionNumber: doc.questionNumber }, { $setOnInsert: doc }, { upsert: true });
  }
  console.log(`Inserted/ensured ${docs.length} questions, numbers 176-${questionNumber - 1}.`);

  await mongoose.disconnect();
}

run().catch((err) => {
  console.error('Add topic questions error:', err);
  process.exit(1);
});
